#!/usr/bin/env python3

from datetime import datetime, timezone
from dateutil import tz
from scapy.all import *
from threading import Thread
from pprint import pprint
import argparse
import csv
import gps
import os
import sqlite3
import time

# Init tracking table for tracking seen APs and improving results with superior RSSIs
sessionTracking = {}

# Init gpsData
gpsData = { "gpsTimestamp": None, "gpsTimestampAge": None, "Longitude": None, "Latitude": None }
# Longitude/Latitude   The location data received at gpsTimestamp.
# gpsTimestamp     The timestamp with that Lon / Lat from GPS
# gpsTimestampAge  The difference in seconds between your host's time and the gpsTimestamp stamp.
#                      Useful to know if your GPS has lost its lock when writing results.


parser = argparse.ArgumentParser()
parser.add_argument("--dbfile",  default='',  help="Enter a relative or full filepath. If not provided a default will be used.")
parser.add_argument("--interface", default='',  help="Interface of choice")
parser.add_argument("--disablechannelswitching", default=False, action='store_true', help="Assume another program is already handling channel switching. We're just along for the ride.")

args = parser.parse_args()

#   ____ _
#  / ___| | __ _ ___ ___  ___  ___
# | |   | |/ _` / __/ __|/ _ \/ __|
# | |___| | (_| \__ \__ \  __/\__ \
#  \____|_|\__,_|___/___/\___||___/
#

class Database: # Our database object
  def __init__(self, databaseFile):
    try:
      self.con = sqlite3.connect(databaseFile,check_same_thread=False)
      self.cur = self.con.cursor()
        # Create our database and a duplicate for evicted(Deemed less accurate) datapoints
      self.exec("create table if not exists wifi \
             (bssid VARCHAR(17),ssid,channel INT,security TEXT,rssi INT,timestamp INT,timestampAge REAL,lat REAL,lon REAL, unique (bssid))")
      self.exec("create table if not exists wifi_evicted \
             (bssid VARCHAR(17),ssid,channel INT,security TEXT,rssi INT,timestamp INT,timestampAge REAL,lat REAL,lon REAL)")
    except Exception as e:
      print('Failed to prepare Database: ', e)
    finally:
      print('Database Connected')

  def exec(self, query):
    self.cur.execute(query)
    self.con.commit()

  def checkBssidExists(self,bssid): # Check if we have a point for a given BSSID already.
    self.exec("select * from wifi where bssid = '%s' limit 1" %(bssid))
    result = self.cur.fetchone()
    if result: # Truthy check for whether we got any result at all.
      #print('BSSID Exists in database already')
      return True
    else:
      #print('BSSID is new')
      return False

  def checkNewPointBetter(self,bssid,ssid,rssi,channel,security,timestamp,timestampAge,lat,lon): # Check if we're replacing stored data.
    self.exec("select * from wifi where bssid = '%s' limit 1" %(bssid))
    stored = self.cur.fetchone()
    if rssi > stored[2]:
      #print('rssi improved')
      return(True)
    else:
      #print('No RSSI improvement, leaving alone.')
      return(False)

  def retirePoint(self,bssid):
    self.exec("INSERT OR REPLACE INTO wifi_evicted select * from wifi where bssid = '%s'" %(bssid))
    self.exec("DELETE from wifi where bssid = '%s'" %(bssid))

  def writePoint(self,bssid,ssid,rssi,channel,security,timestamp,timestampAge,lat,lon):
    self.exec("insert or ignore into wifi values ('%s','%s','%s','%s','%s','%s','%s','%s','%s')" %(bssid,ssid,rssi,channel,security,timestamp,timestampAge,lat,lon))

  def handleWifiPoint(self,bssid,ssid,rssi,channel,security,timestamp,timestampAge,lat,lon):
    if self.checkBssidExists(bssid):
        if self.checkNewPointBetter(bssid,ssid,rssi,channel,security,timestamp,timestampAge,lat,lon):
          self.retirePoint(bssid)
          self.writePoint(bssid,ssid,rssi,channel,security,timestamp,timestampAge,lat,lon)
    else:
      #print('Writing new point: ' + bssid)
      self.writePoint(bssid,ssid,rssi,channel,security,timestamp,timestampAge,lat,lon)



# _____                 _   _
#|  ___|   _ _ __   ___| |_(_) ___  _ __  ___
#| |_ | | | | '_ \ / __| __| |/ _ \| '_ \/ __|
#|  _|| |_| | | | | (__| |_| | (_) | | | \__ \
#|_|   \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
#



def gpsThread(): # Generate GPS data for other threads.
  session = gps.gps(mode=gps.WATCH_ENABLE)
  global gpsData

  while True:
    while 0 == session.read():
      if not (gps.MODE_SET & session.valid): continue

      time=lat=lon=None

      if gps.TIME_SET & session.valid:
        time = session.fix.time
      else: time = None

      if ((gps.isfinite(session.fix.latitude) and gps.isfinite(session.fix.longitude))):
        lat = session.fix.latitude
        lon = session.fix.longitude
      else:
        lat=lon=None

      if time and lat and lon:
        gpsData["gpsTimestamp"] = time
        gpsData["Latitude"]     = lat
        gpsData["Longitude"]    = lon

      # Update drift seconds on stored gpsData
      if gpsData['gpsTimestamp']:
        gpsTime = datetime.strptime(str(gpsData['gpsTimestamp']),'%Y-%m-%dT%H:%M:%S.%f%z')
        gpsTime = gpsTime.replace(tzinfo=tz.tzutc()).astimezone(tz=tz.tzlocal())
        localTime = datetime.now().astimezone()
        gpsData["gpsTimestampAge"] = ((localTime-gpsTime).total_seconds())

    time.sleep(1) # One second sleep between polls should be fine. Make this a variable however. And add arguments to the script.

def processPacket(packet):
  global sessionTracking

  try:
    if packet.haslayer(Dot11Beacon): # If the packet looks good, proceed
      bssid = packet[Dot11].addr2
      ssid  = packet[Dot11Elt].info.decode().rstrip('\x00')
      if len(ssid) == 0: ssid = "<Hidden>"
      rssi = packet.dBm_AntSignal
  
      stats = packet[Dot11Beacon].network_stats()
      channel  = stats.get("channel")
      security = ''.join(stats.get("crypto"))
      
      # Handle new and seen APs. 
      # If new:  Add to array.
      # If seen: Compare RSSI, GPS Coordinates if better.
      
      if not bssid in sessionTracking:
        #print('New: ',bssid, ssid, channel, security,rssi)
        db.handleWifiPoint(bssid,ssid,rssi,channel,security,gpsData['gpsTimestamp'],gpsData['gpsTimestampAge'],gpsData['Latitude'],gpsData['Longitude'])


  except Exception as e: # Ignore busted packets
    print(e)
    pass

def snifferThread():
  sniff(prn=processPacket, iface=interface)


def channelSwitcher():
  print('Channel switching thread started')
  ch = 1
  while True:
    os.system(f"iwconfig {interface} channel {ch}")
    # switch channel from 1 to 14 each 0.5s
    ch = ch % 14 + 1
    time.sleep(0.25)

def waitForGPSLock():
  print('Waiting for GPS lock...')
  while True:
    time.sleep(1)
    if gpsData["gpsTimestamp"] is not None:
      print("Got it:" + str(list(gpsData.values())))
      break

def writeCsv(dbfile):
  global sessionTracking
  global args

  try:
    firstElement = next(iter(sessionTracking))

    with open(dbfile, 'w') as csvFile:
      subKey = list(sessionTracking.keys())[0]
      w = csv.DictWriter(csvFile, sessionTracking[subKey].keys()) # Use first key as CSV formatter for all keys
      w = csv.writer(csvFile)

      w.writerow(sessionTracking[firstElement]) # Use the first element as our CSV header key.

      for AP in list(sessionTracking.keys()): # Loop over all APs and write each to the CSV.
        w.writerow(list(sessionTracking[AP].values()))
  except:
    pass

#  ____
# / ___| ___
#| |  _ / _ \
#| |_| | (_) |
# \____|\___/
#

# We assume bettercap will handle channel switching.

if __name__ == "__main__":
  scriptRoot = os.path.dirname(os.path.realpath(__file__))
  databaseFile = scriptRoot + '/wifi.db'

  if args.interface == '':
    print('We need a --interface to work with!')
    parser.print_help()
    exit(1)

  db = Database(databaseFile)

  interface = args.interface
  gpsThread = Thread(target=gpsThread)
  gpsThread.daemon = True
  gpsThread.start()

  waitForGPSLock()

  snifferThread = Thread(target=snifferThread)
  snifferThread.daemon = True
  snifferThread.start()

  if not args.disablechannelswitching:
    channelSwitcher = Thread(target=channelSwitcher)
    channelSwitcher.daemon = True
    channelSwitcher.start()

  if args.dbfile == '':
    now = datetime.now().strftime("%Y-%m-%d_%H:%M:%S%z")
    dbfile = "./wifigps." + now + ".csv"
    print('Writing to default: ' + dbfile)
  else:
    print('Writing to custom file: ' + args.dbfile)
    dbfile = args.dbfile

  print('Collecting...')

  while True:
    time.sleep(1) # Wait to be killed while threads work their magic.
